### ISSUE TITLE
VsVim line color persists when switching to light theme

### ISSUE THREAD

**Issue by tldrlol** [jonschoning/badwolf-vs#1]
![bugreport](https://cloud.githubusercontent.com/assets/9697324/8945437/08d867ec-3590-11e5-98d8-4fd5db27c5ff.png)

Starting point is F# default settings.
Applied Dark theme.
Imported vs2015 theme file.
Switched to light theme

**Comment by jonschoning** [comment]
Apparently the solution is to restart visual studio after Switching to light theme (then the VsVim line color is correct).
