### ISSUE TITLE
color scheme makes breakpoint margin hard to detect

### ISSUE THREAD

**Issue by tldrlol** [jonschoning/badwolf-vs#2]
![margin1](https://cloud.githubusercontent.com/assets/9697324/8945487/7f831dd8-3590-11e5-87b0-d71e1325c338.PNG)
![margin2](https://cloud.githubusercontent.com/assets/9697324/8945486/7f82a4a2-3590-11e5-9264-9d6706a60e9e.PNG)

**Comment by jonschoning** [comment]
fixed in 7c98c24
